//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServicioReporte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioReporte.IServicioReporte")]
    public interface IServicioReporte {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReporte/Stock", ReplyAction="http://tempuri.org/IServicioReporte/StockResponse")]
        Negocio.Producto[] Stock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReporte/ReporteVentasRealizadas", ReplyAction="http://tempuri.org/IServicioReporte/ReporteVentasRealizadasResponse")]
        Negocio.Pedido[] ReporteVentasRealizadas(System.DateTime FechaDesde, System.DateTime FechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReporte/reporteVentasAnuladas", ReplyAction="http://tempuri.org/IServicioReporte/reporteVentasAnuladasResponse")]
        Negocio.Pedido[] reporteVentasAnuladas(System.DateTime FechaDesde, System.DateTime FechaHasta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioReporteChannel : WebApp.ServicioReporte.IServicioReporte, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReporteClient : System.ServiceModel.ClientBase<WebApp.ServicioReporte.IServicioReporte>, WebApp.ServicioReporte.IServicioReporte {
        
        public ServicioReporteClient() {
        }
        
        public ServicioReporteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReporteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReporteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Negocio.Producto[] Stock() {
            return base.Channel.Stock();
        }
        
        public Negocio.Pedido[] ReporteVentasRealizadas(System.DateTime FechaDesde, System.DateTime FechaHasta) {
            return base.Channel.ReporteVentasRealizadas(FechaDesde, FechaHasta);
        }
        
        public Negocio.Pedido[] reporteVentasAnuladas(System.DateTime FechaDesde, System.DateTime FechaHasta) {
            return base.Channel.reporteVentasAnuladas(FechaDesde, FechaHasta);
        }
    }
}
