//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Entity;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Modelo", "CATEGORIA_PRODUCTO_FK", "CATEGORIA_PRODUCTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.CATEGORIA_PRODUCTO), "PRODUCTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.PRODUCTO), true)]
[assembly: EdmRelationshipAttribute("Modelo", "RUN_CLIENTE_FK", "CLIENTE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.CLIENTE), "PEDIDO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.PEDIDO), true)]
[assembly: EdmRelationshipAttribute("Modelo", "ID_PEDIDO_FK", "PEDIDO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.PEDIDO), "DETALLE_PEDIDO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.DETALLE_PEDIDO), true)]
[assembly: EdmRelationshipAttribute("Modelo", "ID_PRODUCTO_FK", "PRODUCTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.PRODUCTO), "DETALLE_PEDIDO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.DETALLE_PEDIDO), true)]
[assembly: EdmRelationshipAttribute("Modelo", "ID_ESTADO_FK", "ESTADO_PEDIDO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.ESTADO_PEDIDO), "PEDIDO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.PEDIDO), true)]
[assembly: EdmRelationshipAttribute("Modelo", "TIPO_PRODUCTO_FK", "TIPO_PRODUCTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.TIPO_PRODUCTO), "PRODUCTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.PRODUCTO), true)]

#endregion

namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entidades : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entidades object using the connection string found in the 'Entidades' section of the application configuration file.
        /// </summary>
        public Entidades() : base("name=Entidades", "Entidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entidades object.
        /// </summary>
        public Entidades(string connectionString) : base(connectionString, "Entidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entidades object.
        /// </summary>
        public Entidades(EntityConnection connection) : base(connection, "Entidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CATEGORIA_PRODUCTO> CATEGORIA_PRODUCTO
        {
            get
            {
                if ((_CATEGORIA_PRODUCTO == null))
                {
                    _CATEGORIA_PRODUCTO = base.CreateObjectSet<CATEGORIA_PRODUCTO>("CATEGORIA_PRODUCTO");
                }
                return _CATEGORIA_PRODUCTO;
            }
        }
        private ObjectSet<CATEGORIA_PRODUCTO> _CATEGORIA_PRODUCTO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CLIENTE> CLIENTEs
        {
            get
            {
                if ((_CLIENTEs == null))
                {
                    _CLIENTEs = base.CreateObjectSet<CLIENTE>("CLIENTEs");
                }
                return _CLIENTEs;
            }
        }
        private ObjectSet<CLIENTE> _CLIENTEs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DETALLE_PEDIDO> DETALLE_PEDIDO
        {
            get
            {
                if ((_DETALLE_PEDIDO == null))
                {
                    _DETALLE_PEDIDO = base.CreateObjectSet<DETALLE_PEDIDO>("DETALLE_PEDIDO");
                }
                return _DETALLE_PEDIDO;
            }
        }
        private ObjectSet<DETALLE_PEDIDO> _DETALLE_PEDIDO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EMPLEADO> EMPLEADOes
        {
            get
            {
                if ((_EMPLEADOes == null))
                {
                    _EMPLEADOes = base.CreateObjectSet<EMPLEADO>("EMPLEADOes");
                }
                return _EMPLEADOes;
            }
        }
        private ObjectSet<EMPLEADO> _EMPLEADOes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ESTADO_PEDIDO> ESTADO_PEDIDO
        {
            get
            {
                if ((_ESTADO_PEDIDO == null))
                {
                    _ESTADO_PEDIDO = base.CreateObjectSet<ESTADO_PEDIDO>("ESTADO_PEDIDO");
                }
                return _ESTADO_PEDIDO;
            }
        }
        private ObjectSet<ESTADO_PEDIDO> _ESTADO_PEDIDO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PEDIDO> PEDIDOes
        {
            get
            {
                if ((_PEDIDOes == null))
                {
                    _PEDIDOes = base.CreateObjectSet<PEDIDO>("PEDIDOes");
                }
                return _PEDIDOes;
            }
        }
        private ObjectSet<PEDIDO> _PEDIDOes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PRODUCTO> PRODUCTOes
        {
            get
            {
                if ((_PRODUCTOes == null))
                {
                    _PRODUCTOes = base.CreateObjectSet<PRODUCTO>("PRODUCTOes");
                }
                return _PRODUCTOes;
            }
        }
        private ObjectSet<PRODUCTO> _PRODUCTOes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TIPO_PRODUCTO> TIPO_PRODUCTO
        {
            get
            {
                if ((_TIPO_PRODUCTO == null))
                {
                    _TIPO_PRODUCTO = base.CreateObjectSet<TIPO_PRODUCTO>("TIPO_PRODUCTO");
                }
                return _TIPO_PRODUCTO;
            }
        }
        private ObjectSet<TIPO_PRODUCTO> _TIPO_PRODUCTO;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CATEGORIA_PRODUCTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCATEGORIA_PRODUCTO(CATEGORIA_PRODUCTO cATEGORIA_PRODUCTO)
        {
            base.AddObject("CATEGORIA_PRODUCTO", cATEGORIA_PRODUCTO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CLIENTEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCLIENTEs(CLIENTE cLIENTE)
        {
            base.AddObject("CLIENTEs", cLIENTE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DETALLE_PEDIDO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDETALLE_PEDIDO(DETALLE_PEDIDO dETALLE_PEDIDO)
        {
            base.AddObject("DETALLE_PEDIDO", dETALLE_PEDIDO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EMPLEADOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEMPLEADOes(EMPLEADO eMPLEADO)
        {
            base.AddObject("EMPLEADOes", eMPLEADO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ESTADO_PEDIDO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToESTADO_PEDIDO(ESTADO_PEDIDO eSTADO_PEDIDO)
        {
            base.AddObject("ESTADO_PEDIDO", eSTADO_PEDIDO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PEDIDOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPEDIDOes(PEDIDO pEDIDO)
        {
            base.AddObject("PEDIDOes", pEDIDO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PRODUCTOes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPRODUCTOes(PRODUCTO pRODUCTO)
        {
            base.AddObject("PRODUCTOes", pRODUCTO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TIPO_PRODUCTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTIPO_PRODUCTO(TIPO_PRODUCTO tIPO_PRODUCTO)
        {
            base.AddObject("TIPO_PRODUCTO", tIPO_PRODUCTO);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="CATEGORIA_PRODUCTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CATEGORIA_PRODUCTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CATEGORIA_PRODUCTO object.
        /// </summary>
        /// <param name="iD_CATEGORIA">Initial value of the ID_CATEGORIA property.</param>
        /// <param name="cATEGORIA">Initial value of the CATEGORIA property.</param>
        public static CATEGORIA_PRODUCTO CreateCATEGORIA_PRODUCTO(global::System.Decimal iD_CATEGORIA, global::System.String cATEGORIA)
        {
            CATEGORIA_PRODUCTO cATEGORIA_PRODUCTO = new CATEGORIA_PRODUCTO();
            cATEGORIA_PRODUCTO.ID_CATEGORIA = iD_CATEGORIA;
            cATEGORIA_PRODUCTO.CATEGORIA = cATEGORIA;
            return cATEGORIA_PRODUCTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_CATEGORIA
        {
            get
            {
                return _ID_CATEGORIA;
            }
            set
            {
                if (_ID_CATEGORIA != value)
                {
                    OnID_CATEGORIAChanging(value);
                    ReportPropertyChanging("ID_CATEGORIA");
                    _ID_CATEGORIA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_CATEGORIA");
                    OnID_CATEGORIAChanged();
                }
            }
        }
        private global::System.Decimal _ID_CATEGORIA;
        partial void OnID_CATEGORIAChanging(global::System.Decimal value);
        partial void OnID_CATEGORIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CATEGORIA
        {
            get
            {
                return _CATEGORIA;
            }
            set
            {
                OnCATEGORIAChanging(value);
                ReportPropertyChanging("CATEGORIA");
                _CATEGORIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CATEGORIA");
                OnCATEGORIAChanged();
            }
        }
        private global::System.String _CATEGORIA;
        partial void OnCATEGORIAChanging(global::System.String value);
        partial void OnCATEGORIAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "CATEGORIA_PRODUCTO_FK", "PRODUCTO")]
        public EntityCollection<PRODUCTO> PRODUCTOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PRODUCTO>("Modelo.CATEGORIA_PRODUCTO_FK", "PRODUCTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PRODUCTO>("Modelo.CATEGORIA_PRODUCTO_FK", "PRODUCTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="CLIENTE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENTE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CLIENTE object.
        /// </summary>
        /// <param name="cLIENTE_RUN">Initial value of the CLIENTE_RUN property.</param>
        /// <param name="nOMBRE_COMPLETO">Initial value of the NOMBRE_COMPLETO property.</param>
        /// <param name="dIRECCION">Initial value of the DIRECCION property.</param>
        /// <param name="cOMUNA">Initial value of the COMUNA property.</param>
        /// <param name="pROVINCIA">Initial value of the PROVINCIA property.</param>
        /// <param name="rEGION">Initial value of the REGION property.</param>
        /// <param name="fECHA_NACIMIENTO">Initial value of the FECHA_NACIMIENTO property.</param>
        /// <param name="gENERO">Initial value of the GENERO property.</param>
        /// <param name="cORREO_ELECTRONICO">Initial value of the CORREO_ELECTRONICO property.</param>
        /// <param name="nUMERO_TELEFONICO">Initial value of the NUMERO_TELEFONICO property.</param>
        /// <param name="pASSWORD">Initial value of the PASSWORD property.</param>
        public static CLIENTE CreateCLIENTE(global::System.String cLIENTE_RUN, global::System.String nOMBRE_COMPLETO, global::System.String dIRECCION, global::System.String cOMUNA, global::System.String pROVINCIA, global::System.String rEGION, global::System.DateTime fECHA_NACIMIENTO, global::System.String gENERO, global::System.String cORREO_ELECTRONICO, global::System.String nUMERO_TELEFONICO, global::System.String pASSWORD)
        {
            CLIENTE cLIENTE = new CLIENTE();
            cLIENTE.CLIENTE_RUN = cLIENTE_RUN;
            cLIENTE.NOMBRE_COMPLETO = nOMBRE_COMPLETO;
            cLIENTE.DIRECCION = dIRECCION;
            cLIENTE.COMUNA = cOMUNA;
            cLIENTE.PROVINCIA = pROVINCIA;
            cLIENTE.REGION = rEGION;
            cLIENTE.FECHA_NACIMIENTO = fECHA_NACIMIENTO;
            cLIENTE.GENERO = gENERO;
            cLIENTE.CORREO_ELECTRONICO = cORREO_ELECTRONICO;
            cLIENTE.NUMERO_TELEFONICO = nUMERO_TELEFONICO;
            cLIENTE.PASSWORD = pASSWORD;
            return cLIENTE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CLIENTE_RUN
        {
            get
            {
                return _CLIENTE_RUN;
            }
            set
            {
                if (_CLIENTE_RUN != value)
                {
                    OnCLIENTE_RUNChanging(value);
                    ReportPropertyChanging("CLIENTE_RUN");
                    _CLIENTE_RUN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CLIENTE_RUN");
                    OnCLIENTE_RUNChanged();
                }
            }
        }
        private global::System.String _CLIENTE_RUN;
        partial void OnCLIENTE_RUNChanging(global::System.String value);
        partial void OnCLIENTE_RUNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE_COMPLETO
        {
            get
            {
                return _NOMBRE_COMPLETO;
            }
            set
            {
                OnNOMBRE_COMPLETOChanging(value);
                ReportPropertyChanging("NOMBRE_COMPLETO");
                _NOMBRE_COMPLETO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE_COMPLETO");
                OnNOMBRE_COMPLETOChanged();
            }
        }
        private global::System.String _NOMBRE_COMPLETO;
        partial void OnNOMBRE_COMPLETOChanging(global::System.String value);
        partial void OnNOMBRE_COMPLETOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DIRECCION
        {
            get
            {
                return _DIRECCION;
            }
            set
            {
                OnDIRECCIONChanging(value);
                ReportPropertyChanging("DIRECCION");
                _DIRECCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DIRECCION");
                OnDIRECCIONChanged();
            }
        }
        private global::System.String _DIRECCION;
        partial void OnDIRECCIONChanging(global::System.String value);
        partial void OnDIRECCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String COMUNA
        {
            get
            {
                return _COMUNA;
            }
            set
            {
                OnCOMUNAChanging(value);
                ReportPropertyChanging("COMUNA");
                _COMUNA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("COMUNA");
                OnCOMUNAChanged();
            }
        }
        private global::System.String _COMUNA;
        partial void OnCOMUNAChanging(global::System.String value);
        partial void OnCOMUNAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PROVINCIA
        {
            get
            {
                return _PROVINCIA;
            }
            set
            {
                OnPROVINCIAChanging(value);
                ReportPropertyChanging("PROVINCIA");
                _PROVINCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PROVINCIA");
                OnPROVINCIAChanged();
            }
        }
        private global::System.String _PROVINCIA;
        partial void OnPROVINCIAChanging(global::System.String value);
        partial void OnPROVINCIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String REGION
        {
            get
            {
                return _REGION;
            }
            set
            {
                OnREGIONChanging(value);
                ReportPropertyChanging("REGION");
                _REGION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("REGION");
                OnREGIONChanged();
            }
        }
        private global::System.String _REGION;
        partial void OnREGIONChanging(global::System.String value);
        partial void OnREGIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_NACIMIENTO
        {
            get
            {
                return _FECHA_NACIMIENTO;
            }
            set
            {
                OnFECHA_NACIMIENTOChanging(value);
                ReportPropertyChanging("FECHA_NACIMIENTO");
                _FECHA_NACIMIENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_NACIMIENTO");
                OnFECHA_NACIMIENTOChanged();
            }
        }
        private global::System.DateTime _FECHA_NACIMIENTO;
        partial void OnFECHA_NACIMIENTOChanging(global::System.DateTime value);
        partial void OnFECHA_NACIMIENTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GENERO
        {
            get
            {
                return _GENERO;
            }
            set
            {
                OnGENEROChanging(value);
                ReportPropertyChanging("GENERO");
                _GENERO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GENERO");
                OnGENEROChanged();
            }
        }
        private global::System.String _GENERO;
        partial void OnGENEROChanging(global::System.String value);
        partial void OnGENEROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CORREO_ELECTRONICO
        {
            get
            {
                return _CORREO_ELECTRONICO;
            }
            set
            {
                OnCORREO_ELECTRONICOChanging(value);
                ReportPropertyChanging("CORREO_ELECTRONICO");
                _CORREO_ELECTRONICO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CORREO_ELECTRONICO");
                OnCORREO_ELECTRONICOChanged();
            }
        }
        private global::System.String _CORREO_ELECTRONICO;
        partial void OnCORREO_ELECTRONICOChanging(global::System.String value);
        partial void OnCORREO_ELECTRONICOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_TELEFONICO
        {
            get
            {
                return _NUMERO_TELEFONICO;
            }
            set
            {
                OnNUMERO_TELEFONICOChanging(value);
                ReportPropertyChanging("NUMERO_TELEFONICO");
                _NUMERO_TELEFONICO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_TELEFONICO");
                OnNUMERO_TELEFONICOChanged();
            }
        }
        private global::System.String _NUMERO_TELEFONICO;
        partial void OnNUMERO_TELEFONICOChanging(global::System.String value);
        partial void OnNUMERO_TELEFONICOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "RUN_CLIENTE_FK", "PEDIDO")]
        public EntityCollection<PEDIDO> PEDIDOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PEDIDO>("Modelo.RUN_CLIENTE_FK", "PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PEDIDO>("Modelo.RUN_CLIENTE_FK", "PEDIDO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="DETALLE_PEDIDO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DETALLE_PEDIDO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DETALLE_PEDIDO object.
        /// </summary>
        /// <param name="iD_DETALLE">Initial value of the ID_DETALLE property.</param>
        /// <param name="iD_PEDIDO">Initial value of the ID_PEDIDO property.</param>
        /// <param name="iD_PRODUCTO">Initial value of the ID_PRODUCTO property.</param>
        /// <param name="cANTIDAD">Initial value of the CANTIDAD property.</param>
        public static DETALLE_PEDIDO CreateDETALLE_PEDIDO(global::System.Decimal iD_DETALLE, global::System.Decimal iD_PEDIDO, global::System.Decimal iD_PRODUCTO, global::System.Decimal cANTIDAD)
        {
            DETALLE_PEDIDO dETALLE_PEDIDO = new DETALLE_PEDIDO();
            dETALLE_PEDIDO.ID_DETALLE = iD_DETALLE;
            dETALLE_PEDIDO.ID_PEDIDO = iD_PEDIDO;
            dETALLE_PEDIDO.ID_PRODUCTO = iD_PRODUCTO;
            dETALLE_PEDIDO.CANTIDAD = cANTIDAD;
            return dETALLE_PEDIDO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_DETALLE
        {
            get
            {
                return _ID_DETALLE;
            }
            set
            {
                if (_ID_DETALLE != value)
                {
                    OnID_DETALLEChanging(value);
                    ReportPropertyChanging("ID_DETALLE");
                    _ID_DETALLE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_DETALLE");
                    OnID_DETALLEChanged();
                }
            }
        }
        private global::System.Decimal _ID_DETALLE;
        partial void OnID_DETALLEChanging(global::System.Decimal value);
        partial void OnID_DETALLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_PEDIDO
        {
            get
            {
                return _ID_PEDIDO;
            }
            set
            {
                OnID_PEDIDOChanging(value);
                ReportPropertyChanging("ID_PEDIDO");
                _ID_PEDIDO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_PEDIDO");
                OnID_PEDIDOChanged();
            }
        }
        private global::System.Decimal _ID_PEDIDO;
        partial void OnID_PEDIDOChanging(global::System.Decimal value);
        partial void OnID_PEDIDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_PRODUCTO
        {
            get
            {
                return _ID_PRODUCTO;
            }
            set
            {
                OnID_PRODUCTOChanging(value);
                ReportPropertyChanging("ID_PRODUCTO");
                _ID_PRODUCTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_PRODUCTO");
                OnID_PRODUCTOChanged();
            }
        }
        private global::System.Decimal _ID_PRODUCTO;
        partial void OnID_PRODUCTOChanging(global::System.Decimal value);
        partial void OnID_PRODUCTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CANTIDAD
        {
            get
            {
                return _CANTIDAD;
            }
            set
            {
                OnCANTIDADChanging(value);
                ReportPropertyChanging("CANTIDAD");
                _CANTIDAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CANTIDAD");
                OnCANTIDADChanged();
            }
        }
        private global::System.Decimal _CANTIDAD;
        partial void OnCANTIDADChanging(global::System.Decimal value);
        partial void OnCANTIDADChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "ID_PEDIDO_FK", "PEDIDO")]
        public PEDIDO PEDIDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PEDIDO>("Modelo.ID_PEDIDO_FK", "PEDIDO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PEDIDO>("Modelo.ID_PEDIDO_FK", "PEDIDO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PEDIDO> PEDIDOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PEDIDO>("Modelo.ID_PEDIDO_FK", "PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PEDIDO>("Modelo.ID_PEDIDO_FK", "PEDIDO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "ID_PRODUCTO_FK", "PRODUCTO")]
        public PRODUCTO PRODUCTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTO>("Modelo.ID_PRODUCTO_FK", "PRODUCTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTO>("Modelo.ID_PRODUCTO_FK", "PRODUCTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRODUCTO> PRODUCTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRODUCTO>("Modelo.ID_PRODUCTO_FK", "PRODUCTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRODUCTO>("Modelo.ID_PRODUCTO_FK", "PRODUCTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="EMPLEADO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EMPLEADO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EMPLEADO object.
        /// </summary>
        /// <param name="rUN">Initial value of the RUN property.</param>
        /// <param name="fECHA_CONTRATO">Initial value of the FECHA_CONTRATO property.</param>
        /// <param name="sUELDO_LIQUIDO">Initial value of the SUELDO_LIQUIDO property.</param>
        /// <param name="sUELDO_BRUTO">Initial value of the SUELDO_BRUTO property.</param>
        /// <param name="tIPO">Initial value of the TIPO property.</param>
        /// <param name="nOMBRE">Initial value of the NOMBRE property.</param>
        /// <param name="cOMUNA">Initial value of the COMUNA property.</param>
        /// <param name="pROVINCIA">Initial value of the PROVINCIA property.</param>
        /// <param name="rEGION">Initial value of the REGION property.</param>
        /// <param name="fECHA_NACIMIENTO">Initial value of the FECHA_NACIMIENTO property.</param>
        /// <param name="gENERO">Initial value of the GENERO property.</param>
        /// <param name="cORREO_ELECTRONICO">Initial value of the CORREO_ELECTRONICO property.</param>
        /// <param name="nUMERO_TELEFONICO">Initial value of the NUMERO_TELEFONICO property.</param>
        /// <param name="pASSWORD">Initial value of the PASSWORD property.</param>
        public static EMPLEADO CreateEMPLEADO(global::System.String rUN, global::System.DateTime fECHA_CONTRATO, global::System.Decimal sUELDO_LIQUIDO, global::System.Decimal sUELDO_BRUTO, global::System.String tIPO, global::System.String nOMBRE, global::System.String cOMUNA, global::System.String pROVINCIA, global::System.String rEGION, global::System.DateTime fECHA_NACIMIENTO, global::System.String gENERO, global::System.String cORREO_ELECTRONICO, global::System.String nUMERO_TELEFONICO, global::System.String pASSWORD)
        {
            EMPLEADO eMPLEADO = new EMPLEADO();
            eMPLEADO.RUN = rUN;
            eMPLEADO.FECHA_CONTRATO = fECHA_CONTRATO;
            eMPLEADO.SUELDO_LIQUIDO = sUELDO_LIQUIDO;
            eMPLEADO.SUELDO_BRUTO = sUELDO_BRUTO;
            eMPLEADO.TIPO = tIPO;
            eMPLEADO.NOMBRE = nOMBRE;
            eMPLEADO.COMUNA = cOMUNA;
            eMPLEADO.PROVINCIA = pROVINCIA;
            eMPLEADO.REGION = rEGION;
            eMPLEADO.FECHA_NACIMIENTO = fECHA_NACIMIENTO;
            eMPLEADO.GENERO = gENERO;
            eMPLEADO.CORREO_ELECTRONICO = cORREO_ELECTRONICO;
            eMPLEADO.NUMERO_TELEFONICO = nUMERO_TELEFONICO;
            eMPLEADO.PASSWORD = pASSWORD;
            return eMPLEADO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUN
        {
            get
            {
                return _RUN;
            }
            set
            {
                if (_RUN != value)
                {
                    OnRUNChanging(value);
                    ReportPropertyChanging("RUN");
                    _RUN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RUN");
                    OnRUNChanged();
                }
            }
        }
        private global::System.String _RUN;
        partial void OnRUNChanging(global::System.String value);
        partial void OnRUNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_CONTRATO
        {
            get
            {
                return _FECHA_CONTRATO;
            }
            set
            {
                OnFECHA_CONTRATOChanging(value);
                ReportPropertyChanging("FECHA_CONTRATO");
                _FECHA_CONTRATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_CONTRATO");
                OnFECHA_CONTRATOChanged();
            }
        }
        private global::System.DateTime _FECHA_CONTRATO;
        partial void OnFECHA_CONTRATOChanging(global::System.DateTime value);
        partial void OnFECHA_CONTRATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SUELDO_LIQUIDO
        {
            get
            {
                return _SUELDO_LIQUIDO;
            }
            set
            {
                OnSUELDO_LIQUIDOChanging(value);
                ReportPropertyChanging("SUELDO_LIQUIDO");
                _SUELDO_LIQUIDO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUELDO_LIQUIDO");
                OnSUELDO_LIQUIDOChanged();
            }
        }
        private global::System.Decimal _SUELDO_LIQUIDO;
        partial void OnSUELDO_LIQUIDOChanging(global::System.Decimal value);
        partial void OnSUELDO_LIQUIDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SUELDO_BRUTO
        {
            get
            {
                return _SUELDO_BRUTO;
            }
            set
            {
                OnSUELDO_BRUTOChanging(value);
                ReportPropertyChanging("SUELDO_BRUTO");
                _SUELDO_BRUTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUELDO_BRUTO");
                OnSUELDO_BRUTOChanged();
            }
        }
        private global::System.Decimal _SUELDO_BRUTO;
        partial void OnSUELDO_BRUTOChanging(global::System.Decimal value);
        partial void OnSUELDO_BRUTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.String _TIPO;
        partial void OnTIPOChanging(global::System.String value);
        partial void OnTIPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIRECCION
        {
            get
            {
                return _DIRECCION;
            }
            set
            {
                OnDIRECCIONChanging(value);
                ReportPropertyChanging("DIRECCION");
                _DIRECCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIRECCION");
                OnDIRECCIONChanged();
            }
        }
        private global::System.String _DIRECCION;
        partial void OnDIRECCIONChanging(global::System.String value);
        partial void OnDIRECCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String COMUNA
        {
            get
            {
                return _COMUNA;
            }
            set
            {
                OnCOMUNAChanging(value);
                ReportPropertyChanging("COMUNA");
                _COMUNA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("COMUNA");
                OnCOMUNAChanged();
            }
        }
        private global::System.String _COMUNA;
        partial void OnCOMUNAChanging(global::System.String value);
        partial void OnCOMUNAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PROVINCIA
        {
            get
            {
                return _PROVINCIA;
            }
            set
            {
                OnPROVINCIAChanging(value);
                ReportPropertyChanging("PROVINCIA");
                _PROVINCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PROVINCIA");
                OnPROVINCIAChanged();
            }
        }
        private global::System.String _PROVINCIA;
        partial void OnPROVINCIAChanging(global::System.String value);
        partial void OnPROVINCIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String REGION
        {
            get
            {
                return _REGION;
            }
            set
            {
                OnREGIONChanging(value);
                ReportPropertyChanging("REGION");
                _REGION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("REGION");
                OnREGIONChanged();
            }
        }
        private global::System.String _REGION;
        partial void OnREGIONChanging(global::System.String value);
        partial void OnREGIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_NACIMIENTO
        {
            get
            {
                return _FECHA_NACIMIENTO;
            }
            set
            {
                OnFECHA_NACIMIENTOChanging(value);
                ReportPropertyChanging("FECHA_NACIMIENTO");
                _FECHA_NACIMIENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_NACIMIENTO");
                OnFECHA_NACIMIENTOChanged();
            }
        }
        private global::System.DateTime _FECHA_NACIMIENTO;
        partial void OnFECHA_NACIMIENTOChanging(global::System.DateTime value);
        partial void OnFECHA_NACIMIENTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GENERO
        {
            get
            {
                return _GENERO;
            }
            set
            {
                OnGENEROChanging(value);
                ReportPropertyChanging("GENERO");
                _GENERO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GENERO");
                OnGENEROChanged();
            }
        }
        private global::System.String _GENERO;
        partial void OnGENEROChanging(global::System.String value);
        partial void OnGENEROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CORREO_ELECTRONICO
        {
            get
            {
                return _CORREO_ELECTRONICO;
            }
            set
            {
                OnCORREO_ELECTRONICOChanging(value);
                ReportPropertyChanging("CORREO_ELECTRONICO");
                _CORREO_ELECTRONICO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CORREO_ELECTRONICO");
                OnCORREO_ELECTRONICOChanged();
            }
        }
        private global::System.String _CORREO_ELECTRONICO;
        partial void OnCORREO_ELECTRONICOChanging(global::System.String value);
        partial void OnCORREO_ELECTRONICOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_TELEFONICO
        {
            get
            {
                return _NUMERO_TELEFONICO;
            }
            set
            {
                OnNUMERO_TELEFONICOChanging(value);
                ReportPropertyChanging("NUMERO_TELEFONICO");
                _NUMERO_TELEFONICO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_TELEFONICO");
                OnNUMERO_TELEFONICOChanged();
            }
        }
        private global::System.String _NUMERO_TELEFONICO;
        partial void OnNUMERO_TELEFONICOChanging(global::System.String value);
        partial void OnNUMERO_TELEFONICOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="ESTADO_PEDIDO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ESTADO_PEDIDO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ESTADO_PEDIDO object.
        /// </summary>
        /// <param name="iD_ESTADO">Initial value of the ID_ESTADO property.</param>
        /// <param name="eSTADO">Initial value of the ESTADO property.</param>
        public static ESTADO_PEDIDO CreateESTADO_PEDIDO(global::System.Decimal iD_ESTADO, global::System.String eSTADO)
        {
            ESTADO_PEDIDO eSTADO_PEDIDO = new ESTADO_PEDIDO();
            eSTADO_PEDIDO.ID_ESTADO = iD_ESTADO;
            eSTADO_PEDIDO.ESTADO = eSTADO;
            return eSTADO_PEDIDO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_ESTADO
        {
            get
            {
                return _ID_ESTADO;
            }
            set
            {
                if (_ID_ESTADO != value)
                {
                    OnID_ESTADOChanging(value);
                    ReportPropertyChanging("ID_ESTADO");
                    _ID_ESTADO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_ESTADO");
                    OnID_ESTADOChanged();
                }
            }
        }
        private global::System.Decimal _ID_ESTADO;
        partial void OnID_ESTADOChanging(global::System.Decimal value);
        partial void OnID_ESTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "ID_ESTADO_FK", "PEDIDO")]
        public EntityCollection<PEDIDO> PEDIDOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PEDIDO>("Modelo.ID_ESTADO_FK", "PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PEDIDO>("Modelo.ID_ESTADO_FK", "PEDIDO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="PEDIDO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PEDIDO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PEDIDO object.
        /// </summary>
        /// <param name="iD_PEDIDO">Initial value of the ID_PEDIDO property.</param>
        /// <param name="fORMA_ENTREGA">Initial value of the FORMA_ENTREGA property.</param>
        /// <param name="cOMENTARIO">Initial value of the COMENTARIO property.</param>
        /// <param name="tOTAL_VENTA">Initial value of the TOTAL_VENTA property.</param>
        /// <param name="fECHA_HORA">Initial value of the FECHA_HORA property.</param>
        /// <param name="rUN_CLIENTE">Initial value of the RUN_CLIENTE property.</param>
        /// <param name="iD_ESTADO">Initial value of the ID_ESTADO property.</param>
        public static PEDIDO CreatePEDIDO(global::System.Decimal iD_PEDIDO, global::System.String fORMA_ENTREGA, global::System.String cOMENTARIO, global::System.Decimal tOTAL_VENTA, global::System.DateTime fECHA_HORA, global::System.String rUN_CLIENTE, global::System.Decimal iD_ESTADO)
        {
            PEDIDO pEDIDO = new PEDIDO();
            pEDIDO.ID_PEDIDO = iD_PEDIDO;
            pEDIDO.FORMA_ENTREGA = fORMA_ENTREGA;
            pEDIDO.COMENTARIO = cOMENTARIO;
            pEDIDO.TOTAL_VENTA = tOTAL_VENTA;
            pEDIDO.FECHA_HORA = fECHA_HORA;
            pEDIDO.RUN_CLIENTE = rUN_CLIENTE;
            pEDIDO.ID_ESTADO = iD_ESTADO;
            return pEDIDO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_PEDIDO
        {
            get
            {
                return _ID_PEDIDO;
            }
            set
            {
                if (_ID_PEDIDO != value)
                {
                    OnID_PEDIDOChanging(value);
                    ReportPropertyChanging("ID_PEDIDO");
                    _ID_PEDIDO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_PEDIDO");
                    OnID_PEDIDOChanged();
                }
            }
        }
        private global::System.Decimal _ID_PEDIDO;
        partial void OnID_PEDIDOChanging(global::System.Decimal value);
        partial void OnID_PEDIDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FORMA_ENTREGA
        {
            get
            {
                return _FORMA_ENTREGA;
            }
            set
            {
                OnFORMA_ENTREGAChanging(value);
                ReportPropertyChanging("FORMA_ENTREGA");
                _FORMA_ENTREGA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FORMA_ENTREGA");
                OnFORMA_ENTREGAChanged();
            }
        }
        private global::System.String _FORMA_ENTREGA;
        partial void OnFORMA_ENTREGAChanging(global::System.String value);
        partial void OnFORMA_ENTREGAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String COMENTARIO
        {
            get
            {
                return _COMENTARIO;
            }
            set
            {
                OnCOMENTARIOChanging(value);
                ReportPropertyChanging("COMENTARIO");
                _COMENTARIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("COMENTARIO");
                OnCOMENTARIOChanged();
            }
        }
        private global::System.String _COMENTARIO;
        partial void OnCOMENTARIOChanging(global::System.String value);
        partial void OnCOMENTARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TOTAL_VENTA
        {
            get
            {
                return _TOTAL_VENTA;
            }
            set
            {
                OnTOTAL_VENTAChanging(value);
                ReportPropertyChanging("TOTAL_VENTA");
                _TOTAL_VENTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TOTAL_VENTA");
                OnTOTAL_VENTAChanged();
            }
        }
        private global::System.Decimal _TOTAL_VENTA;
        partial void OnTOTAL_VENTAChanging(global::System.Decimal value);
        partial void OnTOTAL_VENTAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_HORA
        {
            get
            {
                return _FECHA_HORA;
            }
            set
            {
                OnFECHA_HORAChanging(value);
                ReportPropertyChanging("FECHA_HORA");
                _FECHA_HORA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_HORA");
                OnFECHA_HORAChanged();
            }
        }
        private global::System.DateTime _FECHA_HORA;
        partial void OnFECHA_HORAChanging(global::System.DateTime value);
        partial void OnFECHA_HORAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUN_CLIENTE
        {
            get
            {
                return _RUN_CLIENTE;
            }
            set
            {
                OnRUN_CLIENTEChanging(value);
                ReportPropertyChanging("RUN_CLIENTE");
                _RUN_CLIENTE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RUN_CLIENTE");
                OnRUN_CLIENTEChanged();
            }
        }
        private global::System.String _RUN_CLIENTE;
        partial void OnRUN_CLIENTEChanging(global::System.String value);
        partial void OnRUN_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_ESTADO
        {
            get
            {
                return _ID_ESTADO;
            }
            set
            {
                OnID_ESTADOChanging(value);
                ReportPropertyChanging("ID_ESTADO");
                _ID_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_ESTADO");
                OnID_ESTADOChanged();
            }
        }
        private global::System.Decimal _ID_ESTADO;
        partial void OnID_ESTADOChanging(global::System.Decimal value);
        partial void OnID_ESTADOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "RUN_CLIENTE_FK", "CLIENTE")]
        public CLIENTE CLIENTE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("Modelo.RUN_CLIENTE_FK", "CLIENTE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("Modelo.RUN_CLIENTE_FK", "CLIENTE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENTE> CLIENTEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTE>("Modelo.RUN_CLIENTE_FK", "CLIENTE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENTE>("Modelo.RUN_CLIENTE_FK", "CLIENTE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "ID_PEDIDO_FK", "DETALLE_PEDIDO")]
        public EntityCollection<DETALLE_PEDIDO> DETALLE_PEDIDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DETALLE_PEDIDO>("Modelo.ID_PEDIDO_FK", "DETALLE_PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DETALLE_PEDIDO>("Modelo.ID_PEDIDO_FK", "DETALLE_PEDIDO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "ID_ESTADO_FK", "ESTADO_PEDIDO")]
        public ESTADO_PEDIDO ESTADO_PEDIDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ESTADO_PEDIDO>("Modelo.ID_ESTADO_FK", "ESTADO_PEDIDO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ESTADO_PEDIDO>("Modelo.ID_ESTADO_FK", "ESTADO_PEDIDO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ESTADO_PEDIDO> ESTADO_PEDIDOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ESTADO_PEDIDO>("Modelo.ID_ESTADO_FK", "ESTADO_PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ESTADO_PEDIDO>("Modelo.ID_ESTADO_FK", "ESTADO_PEDIDO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="PRODUCTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUCTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PRODUCTO object.
        /// </summary>
        /// <param name="iD_PRODUCTO">Initial value of the ID_PRODUCTO property.</param>
        /// <param name="sTOCK">Initial value of the STOCK property.</param>
        /// <param name="nOMBRE">Initial value of the NOMBRE property.</param>
        /// <param name="pRECIO_NORMAL">Initial value of the PRECIO_NORMAL property.</param>
        /// <param name="pRECIO_OFERTA">Initial value of the PRECIO_OFERTA property.</param>
        /// <param name="eN_OFERTA">Initial value of the EN_OFERTA property.</param>
        /// <param name="dESCRIPCION">Initial value of the DESCRIPCION property.</param>
        /// <param name="cATEGORIA">Initial value of the CATEGORIA property.</param>
        /// <param name="tIPO_PRODUCTO">Initial value of the TIPO_PRODUCTO property.</param>
        public static PRODUCTO CreatePRODUCTO(global::System.Decimal iD_PRODUCTO, global::System.Decimal sTOCK, global::System.String nOMBRE, global::System.Decimal pRECIO_NORMAL, global::System.Decimal pRECIO_OFERTA, global::System.String eN_OFERTA, global::System.String dESCRIPCION, global::System.Decimal cATEGORIA, global::System.Decimal tIPO_PRODUCTO)
        {
            PRODUCTO pRODUCTO = new PRODUCTO();
            pRODUCTO.ID_PRODUCTO = iD_PRODUCTO;
            pRODUCTO.STOCK = sTOCK;
            pRODUCTO.NOMBRE = nOMBRE;
            pRODUCTO.PRECIO_NORMAL = pRECIO_NORMAL;
            pRODUCTO.PRECIO_OFERTA = pRECIO_OFERTA;
            pRODUCTO.EN_OFERTA = eN_OFERTA;
            pRODUCTO.DESCRIPCION = dESCRIPCION;
            pRODUCTO.CATEGORIA = cATEGORIA;
            pRODUCTO.TIPO_PRODUCTO = tIPO_PRODUCTO;
            return pRODUCTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_PRODUCTO
        {
            get
            {
                return _ID_PRODUCTO;
            }
            set
            {
                if (_ID_PRODUCTO != value)
                {
                    OnID_PRODUCTOChanging(value);
                    ReportPropertyChanging("ID_PRODUCTO");
                    _ID_PRODUCTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_PRODUCTO");
                    OnID_PRODUCTOChanged();
                }
            }
        }
        private global::System.Decimal _ID_PRODUCTO;
        partial void OnID_PRODUCTOChanging(global::System.Decimal value);
        partial void OnID_PRODUCTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal STOCK
        {
            get
            {
                return _STOCK;
            }
            set
            {
                OnSTOCKChanging(value);
                ReportPropertyChanging("STOCK");
                _STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STOCK");
                OnSTOCKChanged();
            }
        }
        private global::System.Decimal _STOCK;
        partial void OnSTOCKChanging(global::System.Decimal value);
        partial void OnSTOCKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PRECIO_NORMAL
        {
            get
            {
                return _PRECIO_NORMAL;
            }
            set
            {
                OnPRECIO_NORMALChanging(value);
                ReportPropertyChanging("PRECIO_NORMAL");
                _PRECIO_NORMAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRECIO_NORMAL");
                OnPRECIO_NORMALChanged();
            }
        }
        private global::System.Decimal _PRECIO_NORMAL;
        partial void OnPRECIO_NORMALChanging(global::System.Decimal value);
        partial void OnPRECIO_NORMALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PRECIO_OFERTA
        {
            get
            {
                return _PRECIO_OFERTA;
            }
            set
            {
                OnPRECIO_OFERTAChanging(value);
                ReportPropertyChanging("PRECIO_OFERTA");
                _PRECIO_OFERTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRECIO_OFERTA");
                OnPRECIO_OFERTAChanged();
            }
        }
        private global::System.Decimal _PRECIO_OFERTA;
        partial void OnPRECIO_OFERTAChanging(global::System.Decimal value);
        partial void OnPRECIO_OFERTAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EN_OFERTA
        {
            get
            {
                return _EN_OFERTA;
            }
            set
            {
                OnEN_OFERTAChanging(value);
                ReportPropertyChanging("EN_OFERTA");
                _EN_OFERTA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EN_OFERTA");
                OnEN_OFERTAChanged();
            }
        }
        private global::System.String _EN_OFERTA;
        partial void OnEN_OFERTAChanging(global::System.String value);
        partial void OnEN_OFERTAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCION
        {
            get
            {
                return _DESCRIPCION;
            }
            set
            {
                OnDESCRIPCIONChanging(value);
                ReportPropertyChanging("DESCRIPCION");
                _DESCRIPCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESCRIPCION");
                OnDESCRIPCIONChanged();
            }
        }
        private global::System.String _DESCRIPCION;
        partial void OnDESCRIPCIONChanging(global::System.String value);
        partial void OnDESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CATEGORIA
        {
            get
            {
                return _CATEGORIA;
            }
            set
            {
                OnCATEGORIAChanging(value);
                ReportPropertyChanging("CATEGORIA");
                _CATEGORIA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CATEGORIA");
                OnCATEGORIAChanged();
            }
        }
        private global::System.Decimal _CATEGORIA;
        partial void OnCATEGORIAChanging(global::System.Decimal value);
        partial void OnCATEGORIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TIPO_PRODUCTO
        {
            get
            {
                return _TIPO_PRODUCTO;
            }
            set
            {
                OnTIPO_PRODUCTOChanging(value);
                ReportPropertyChanging("TIPO_PRODUCTO");
                _TIPO_PRODUCTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO_PRODUCTO");
                OnTIPO_PRODUCTOChanged();
            }
        }
        private global::System.Decimal _TIPO_PRODUCTO;
        partial void OnTIPO_PRODUCTOChanging(global::System.Decimal value);
        partial void OnTIPO_PRODUCTOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "CATEGORIA_PRODUCTO_FK", "CATEGORIA_PRODUCTO")]
        public CATEGORIA_PRODUCTO CATEGORIA_PRODUCTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIA_PRODUCTO>("Modelo.CATEGORIA_PRODUCTO_FK", "CATEGORIA_PRODUCTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIA_PRODUCTO>("Modelo.CATEGORIA_PRODUCTO_FK", "CATEGORIA_PRODUCTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CATEGORIA_PRODUCTO> CATEGORIA_PRODUCTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIA_PRODUCTO>("Modelo.CATEGORIA_PRODUCTO_FK", "CATEGORIA_PRODUCTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CATEGORIA_PRODUCTO>("Modelo.CATEGORIA_PRODUCTO_FK", "CATEGORIA_PRODUCTO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "ID_PRODUCTO_FK", "DETALLE_PEDIDO")]
        public EntityCollection<DETALLE_PEDIDO> DETALLE_PEDIDO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DETALLE_PEDIDO>("Modelo.ID_PRODUCTO_FK", "DETALLE_PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DETALLE_PEDIDO>("Modelo.ID_PRODUCTO_FK", "DETALLE_PEDIDO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "TIPO_PRODUCTO_FK", "TIPO_PRODUCTO")]
        public TIPO_PRODUCTO TIPO_PRODUCTO1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_PRODUCTO>("Modelo.TIPO_PRODUCTO_FK", "TIPO_PRODUCTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_PRODUCTO>("Modelo.TIPO_PRODUCTO_FK", "TIPO_PRODUCTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TIPO_PRODUCTO> TIPO_PRODUCTO1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TIPO_PRODUCTO>("Modelo.TIPO_PRODUCTO_FK", "TIPO_PRODUCTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TIPO_PRODUCTO>("Modelo.TIPO_PRODUCTO_FK", "TIPO_PRODUCTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="TIPO_PRODUCTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TIPO_PRODUCTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TIPO_PRODUCTO object.
        /// </summary>
        /// <param name="iD_TIPO_PRODUCTO">Initial value of the ID_TIPO_PRODUCTO property.</param>
        /// <param name="nOMBRE">Initial value of the NOMBRE property.</param>
        public static TIPO_PRODUCTO CreateTIPO_PRODUCTO(global::System.Decimal iD_TIPO_PRODUCTO, global::System.String nOMBRE)
        {
            TIPO_PRODUCTO tIPO_PRODUCTO = new TIPO_PRODUCTO();
            tIPO_PRODUCTO.ID_TIPO_PRODUCTO = iD_TIPO_PRODUCTO;
            tIPO_PRODUCTO.NOMBRE = nOMBRE;
            return tIPO_PRODUCTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_TIPO_PRODUCTO
        {
            get
            {
                return _ID_TIPO_PRODUCTO;
            }
            set
            {
                if (_ID_TIPO_PRODUCTO != value)
                {
                    OnID_TIPO_PRODUCTOChanging(value);
                    ReportPropertyChanging("ID_TIPO_PRODUCTO");
                    _ID_TIPO_PRODUCTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_TIPO_PRODUCTO");
                    OnID_TIPO_PRODUCTOChanged();
                }
            }
        }
        private global::System.Decimal _ID_TIPO_PRODUCTO;
        partial void OnID_TIPO_PRODUCTOChanging(global::System.Decimal value);
        partial void OnID_TIPO_PRODUCTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "TIPO_PRODUCTO_FK", "PRODUCTO")]
        public EntityCollection<PRODUCTO> PRODUCTOes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PRODUCTO>("Modelo.TIPO_PRODUCTO_FK", "PRODUCTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PRODUCTO>("Modelo.TIPO_PRODUCTO_FK", "PRODUCTO", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
