//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServicioCompras {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCompras.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicio/RegistrarUsuarioResponse")]
        bool RegistrarUsuario(Negocio.Cliente nuevoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EditarUsuario", ReplyAction="http://tempuri.org/IServicio/EditarUsuarioResponse")]
        bool EditarUsuario(Negocio.Cliente clienteEditado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarUsuario", ReplyAction="http://tempuri.org/IServicio/EliminarUsuarioResponse")]
        bool EliminarUsuario(string runCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AutenticarCliente", ReplyAction="http://tempuri.org/IServicio/AutenticarClienteResponse")]
        bool AutenticarCliente(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AnularPedido", ReplyAction="http://tempuri.org/IServicio/AnularPedidoResponse")]
        bool AnularPedido(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GenerarPedido", ReplyAction="http://tempuri.org/IServicio/GenerarPedidoResponse")]
        bool GenerarPedido(Negocio.Pedido nuevoPedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : WebApp.ServicioCompras.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<WebApp.ServicioCompras.IServicio>, WebApp.ServicioCompras.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarUsuario(Negocio.Cliente nuevoCliente) {
            return base.Channel.RegistrarUsuario(nuevoCliente);
        }
        
        public bool EditarUsuario(Negocio.Cliente clienteEditado) {
            return base.Channel.EditarUsuario(clienteEditado);
        }
        
        public bool EliminarUsuario(string runCliente) {
            return base.Channel.EliminarUsuario(runCliente);
        }
        
        public bool AutenticarCliente(string correo, string password) {
            return base.Channel.AutenticarCliente(correo, password);
        }
        
        public bool AnularPedido(int idPedido) {
            return base.Channel.AnularPedido(idPedido);
        }
        
        public bool GenerarPedido(Negocio.Pedido nuevoPedido) {
            return base.Channel.GenerarPedido(nuevoPedido);
        }
    }
}
